# Generated by Django 4.1.2 on 2022-10-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0002_url_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='user_id',
            new_name='user',
        ),
    ]
