# Generated by Django 4.1.2 on 2022-10-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0006_alter_url_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='abobys',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
