# Generated by Django 4.1.2 on 2022-10-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0012_url_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_hash',
            field=models.URLField(),
        ),
    ]
